import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import SubSidebar from '../components/SubSidebar';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xtremax WST</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box as='main'>
        <Sidebar>
          <SubSidebar>
            <Navbar>Main Content Here</Navbar>
          </SubSidebar>
        </Sidebar>
      </Box>
    </div>
  );
}
